steps:
  # Build Docker image with build arguments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_KEY=${_NEXT_PUBLIC_API_KEY}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/watchdogs-frontend:${_IMAGE_TAG}'
      - '.'

  # Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/watchdogs-frontend:${_IMAGE_TAG}'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'watchdogs-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/watchdogs-frontend:${_IMAGE_TAG}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/watchdogs-frontend:${_IMAGE_TAG}'

# Default substitution values (can be overridden by GitHub Actions)
substitutions:
  _NEXT_PUBLIC_API_URL: 'https://backup-api-27617992020.us-central1.run.app'
  _NEXT_PUBLIC_API_KEY: 'a7f3e9d2c1b8a4f6e8d9c2b5a7f3e9d2c1b8a4f6e8d9c2b5a7f3e9d2c1b8a4f6'
  _IMAGE_TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY